name: Check new versions and push
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check new versions and push
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: |
          pacman -Syu --noconfirm --noprogressbar --needed base-devel git sudo
          git config --global user.name duament
          git config --global user.email 30264485+duament@users.noreply.github.com
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          useradd -m user
          chown -R user .
      - run: |
          cd vim-youcompleteme-git
          sudo -u user makepkg -d -o --noprepare
          ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
          git add PKGBUILD
          git commit -m "vim-youcompleteme-git: $ver" || true
          git push
          cd ..
      - run: |
          cd sbupdate-git
          sudo -u user makepkg -d -o --noprepare
          ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
          git add PKGBUILD
          git commit -m "sbupdate-git: $ver" || true
          git push
          cd ..
