name: Check new versions and push
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check new versions and push
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: |
          pacman -Syu --noconfirm --noprogressbar --needed base-devel git sudo pacman-contrib
          git config --global user.name duament
          git config --global user.email 30264485+duament@users.noreply.github.com
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          useradd -m user
          chown -R user .
      - run: |
          cd vim-youcompleteme-git
          sudo -u user makepkg -d -o --noprepare
          if ! git diff --quiet
          then
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=1/g" PKGBUILD
            git add PKGBUILD
            git commit -m "vim-youcompleteme-git: $ver"
            git push
          fi
          cd ..
      - run: |
          cd vim-indent-guides-git
          sudo -u user makepkg -d -o --noprepare
          if ! git diff --quiet
          then
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=1/g" PKGBUILD
            git add PKGBUILD
            git commit -m "vim-indent-guides-git: $ver"
            git push
          fi
          cd ..
      - run: |
          cd sbupdate-git
          sudo -u user makepkg -d -o --noprepare
          if ! git diff --quiet
          then
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=1/g" PKGBUILD
            git add PKGBUILD
            git commit -m "sbupdate-git: $ver"
            git push
          fi
          cd ..
      - run: |
          cd nginx-mainline-mod-fancyindex
          nginxver=$(cat nginxver)
          new_nginxver=$(pacman -Si nginx-mainline | grep -m 1 '^Version' | awk '{print $NF}')
          new_nginxver=${new_nginxver%-*}
          if [[ $nginxver != $new_nginxver ]]
          then
            echo $new_nginxver > nginxver
            rel_line=$(grep -m1 'pkgrel=' PKGBUILD)
            rel=$((${rel_line#*=} + 1))
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=$rel/g" PKGBUILD
            sudo -u user updpkgsums
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            git add .
            git commit -m "nginx-mainline-mod-fancyindex: $ver-$rel (nginx $new_nginxver)" || true
            git push
          fi
          cd ..
      - run: |
          cd nginx-mainline-mod-brotli
          nginxver=$(cat nginxver)
          new_nginxver=$(pacman -Si nginx-mainline | grep -m 1 '^Version' | awk '{print $NF}')
          new_nginxver=${new_nginxver%-*}
          if [[ $nginxver != $new_nginxver ]]
          then
            echo $new_nginxver > nginxver
            rel_line=$(grep -m1 'pkgrel=' PKGBUILD)
            rel=$((${rel_line#*=} + 1))
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=$rel/g" PKGBUILD
            sudo -u user updpkgsums
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            git add .
            git commit -m "nginx-mainline-mod-brotli: $ver-$rel (nginx $new_nginxver)" || true
            git push
          fi
          cd ..
      - run: |
          cd nginx-mainline-mod-dav-ext
          nginxver=$(cat nginxver)
          new_nginxver=$(pacman -Si nginx-mainline | grep -m 1 '^Version' | awk '{print $NF}')
          new_nginxver=${new_nginxver%-*}
          if [[ $nginxver != $new_nginxver ]]
          then
            echo $new_nginxver > nginxver
            rel_line=$(grep -m1 'pkgrel=' PKGBUILD)
            rel=$((${rel_line#*=} + 1))
            sed -i -e "s/^\s*pkgrel=.*$/pkgrel=$rel/g" PKGBUILD
            sudo -u user updpkgsums
            ver=$(cat PKGBUILD | grep -m1 pkgver= | cut -d '=' -f2)
            git add .
            git commit -m "nginx-mainline-mod-dav-ext: $ver-$rel (nginx $new_nginxver)" || true
            git push
          fi
          cd ..
