name: Build go.rice
on:
  push:
    paths:
      - 'go.rice/**'
      - '.github/workflows/go.rice.yml'
  workflow_dispatch:

jobs:
  job:
    name: Build go.rice
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - run: |
          pacman -Syu --noconfirm --noprogressbar --needed git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DIR: $GITHUB_WORKSPACE/go.rice
