name: Build mpv-mpris
on:
  push:
    paths:
      - 'mpv-mpris/**'
      - '.github/workflows/mpv-mpris.yml'

jobs:
  job:
    name: Build mpv-mpris
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DIR: $GITHUB_WORKSPACE/mpv-mpris
