name: Build mpv-vapoursynth
on:
  push:
    paths:
      - 'mpv-vapoursynth/**'
      - '.github/workflows/mpv-vapoursynth.yml'
  workflow_dispatch:

jobs:
  job:
    name: Build mpv-vapoursynth
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: |
          pacman -Syu --noconfirm --noprogressbar --needed git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Receive PGP keys
        run: |
          mkdir /gpg_keys
          curl -Ls 'https://github.com/sfan5.gpg' -o /gpg_keys/sfan5
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBKEY_DIR: /gpg_keys
        with:
          DIR: $GITHUB_WORKSPACE/mpv-vapoursynth
