name: Build mpv-vapoursynth
on:
  push:
    paths:
      - 'mpv-vapoursynth/**'
      - '.github/workflows/mpv-vapoursynth.yml'

jobs:
  job:
    name: Build mpv-vapoursynth
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Receive PGP keys
        run: gpg --batch --keyserver https://keyserver.ubuntu.com/ --recv-keys 145077D82501AA20152CACCE8D769208D5E31419
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DIR: $GITHUB_WORKSPACE/mpv-vapoursynth
