name: Build nginx-mainline-mod-dav-ext
on:
  push:
    paths:
      - 'nginx-mainline-mod-dav-ext/**'
      - '.github/workflows/nginx-mainline-mod-dav-ext.yml'
  workflow_dispatch:

jobs:
  job:
    name: Build nginx-mainline-mod-dav-ext
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - run: |
          pacman -Syu --noconfirm --noprogressbar --needed git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DIR: $GITHUB_WORKSPACE/nginx-mainline-mod-dav-ext
