name: Build nginx-mainline-mod-brotli
on:
  push:
    paths:
      - 'nginx-mainline-mod-brotli/**'
      - '.github/workflows/nginx-mainline-mod-brotli.yml'

jobs:
  job:
    name: Build nginx-mainline-mod-brotli
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DIR: $GITHUB_WORKSPACE/nginx-mainline-mod-brotli
