name: Build vim-youcompleteme-git
on:
  push:
    paths:
      - 'vim-youcompleteme-git/**'
      - '.github/workflows/vim-youcompleteme-git.yml'

jobs:
  job:
    name: Build vim-youcompleteme-git
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build python-requests-futures
        id: build_python_requests_futures
        uses: duament/build-arch-package@master
        with:
          PKGBUILD: $GITHUB_WORKSPACE/python-requests-futures
          OUTDIR: $HOME/python-requests-futures
      - id: get-param
        run: |
          param=-I\ ${{ steps.build_python_requests_futures.outputs.pkg_path }}
          echo "::set-output name=param::$param"
      - name: Build Arch Linux packages
        id: build
        uses: duament/build-arch-package@master
        with:
          PKGBUILD: $GITHUB_WORKSPACE/vim-youcompleteme-git
          OUTDIR: $HOME/arch-packages
          PARAM: ${{ steps.get-param.outputs.param }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.pkg_path }}
          asset_name: ${{ steps.build.outputs.pkg_name }}
          asset_content_type: application/zstd
